steps:
  # Install dependencies
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['install']
    dir: 'backend'
    
  # Build the application
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['run', 'build']
    dir: 'backend'
    
  # Package as a container using buildpacks (no Dockerfile needed)
  - name: 'gcr.io/k8s-skaffold/pack'
    entrypoint: 'pack'
    args:
      - 'build'
      - '${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/backend:${COMMIT_SHA}'
      - '--builder=gcr.io/buildpacks/builder:v1'
      - '--path=./backend'
      
  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'backend-service'
      - '--image=${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/backend:${COMMIT_SHA}'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'

images:
  - '${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/backend:${COMMIT_SHA}'

substitutions:
  _LOCATION: europe-west4
  _REPOSITORY: my-repo
  _REGION: europe-west4
