name: Build and Deploy Backend to Cloud Run

on:
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            # Install dependencies
          - name: 'node:20'
            run: |
              cd backend
              npm install
            
            # Build the application
          - name: 'Build Application'
            run: |
              cd backend
              npm run build
                
            # Package as a container using buildpacks (no Dockerfile needed)
          - name: 'Build Container'
            run: |
              pack build ${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/backend:${COMMIT_SHA} \
                --builder=gcr.io/buildpacks/builder:v1 \
                --path=./backend
                
            # Deploy to Cloud Run
          - name: 'Deploy to Cloud Run'
            run: |
              gcloud run deploy backend-service \
                --image=${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/backend:${COMMIT_SHA} \
                --region=${_REGION} \
                --platform=managed \
                --allow-unauthenticated

        env:
          LOCATION: us-central1
          REPOSITORY: my-repo
          REGION: us-central1
